name: kavi Pipeline

on: 
  push:

jobs:
  kavi-test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "CI Pipeline Running"

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Check Python version
        run: python --version
